# Generated by Django 5.2.5 on 2026-08-24 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to='fornecedores.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total da Compra (R$)'),
        ),
    ]
