# Generated by Django 5.2.5 on 2026-08-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_movimentacaoestoque_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Codigo de Barras'),
        ),
    ]
