# Generated by Django 5.2.5 on 2025-08-14 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_checkin', models.DateTimeField(auto_now_add=True, verbose_name='Data do Check-in')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Check-in de Evento',
                'verbose_name_plural': 'Check-ins de Eventos',
                'ordering': ['-data_checkin'],
            },
        ),
        migrations.CreateModel(
            name='ConvidadoEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento (RG/CPF)')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('compareceu', models.BooleanField(default=False, verbose_name='Compareceu')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Convidado de Evento',
                'verbose_name_plural': 'Convidados de Eventos',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('SOCIAL', 'Social'), ('ESPORTIVO', 'Esportivo'), ('CULTURAL', 'Cultural'), ('FAMILIAR', 'Familiar'), ('EMPRESARIAL', 'Empresarial'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Evento')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('endereco', models.CharField(blank=True, max_length=500, null=True, verbose_name='Endereço Completo')),
                ('capacidade_maxima', models.IntegerField(blank=True, null=True, verbose_name='Capacidade Máxima')),
                ('valor_ingresso_socio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Ingresso (Sócio)')),
                ('valor_ingresso_convidado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Ingresso (Convidado)')),
                ('permite_convidados', models.BooleanField(default=True, verbose_name='Permite Convidados')),
                ('max_convidados_por_socio', models.IntegerField(default=2, verbose_name='Máximo de Convidados por Sócio')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/imagens/', verbose_name='Imagem do Evento')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('inscricoes_abertas', models.BooleanField(default=True, verbose_name='Inscrições Abertas')),
                ('requer_confirmacao', models.BooleanField(default=False, verbose_name='Requer Confirmação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_convidados', models.IntegerField(default=0, verbose_name='Quantidade de Convidados')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('NAO_COMPARECEU', 'Não Compareceu')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('forma_pagamento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Forma de Pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Inscrição em Evento',
                'verbose_name_plural': 'Inscrições em Eventos',
                'ordering': ['-data_inscricao'],
            },
        ),
    ]
