# Generated by Django 5.2.5 on 2025-08-14 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinevento',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_eventos', to='socios.socio', verbose_name='Sócio'),
        ),
    ]
