# Generated by Django 5.2.5 on 2025-08-14 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0002_initial'),
        ('socios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinevento',
            name='usuario_checkin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Check-in'),
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL, verbose_name='Organizador'),
        ),
        migrations.AddField(
            model_name='checkinevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='eventos.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='inscricaoevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='inscricaoevento',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_eventos', to='socios.socio', verbose_name='Sócio'),
        ),
        migrations.AddField(
            model_name='inscricaoevento',
            name='usuario_cadastro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Cadastro'),
        ),
        migrations.AddField(
            model_name='convidadoevento',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convidados', to='eventos.inscricaoevento', verbose_name='Inscrição'),
        ),
        migrations.AddField(
            model_name='checkinevento',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='eventos.inscricaoevento', verbose_name='Inscrição'),
        ),
        migrations.AlterUniqueTogether(
            name='inscricaoevento',
            unique_together={('evento', 'socio')},
        ),
        migrations.AlterUniqueTogether(
            name='checkinevento',
            unique_together={('evento', 'socio')},
        ),
    ]
