# Generated by Django 5.2.5 on 2025-08-14 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('CREATE', 'Criar'), ('UPDATE', 'Atualizar'), ('DELETE', 'Excluir'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar')], max_length=20, verbose_name='Ação')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.CharField(max_length=100, verbose_name='ID do Objeto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('dados_antigos', models.JSONField(blank=True, null=True, verbose_name='Dados Antigos')),
                ('dados_novos', models.JSONField(blank=True, null=True, verbose_name='Dados Novos')),
                ('data_acao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-data_acao'],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Backup')),
                ('tipo', models.CharField(choices=[('COMPLETO', 'Completo'), ('DADOS', 'Apenas Dados'), ('ARQUIVOS', 'Apenas Arquivos')], max_length=20, verbose_name='Tipo de Backup')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='backups/', verbose_name='Arquivo de Backup')),
                ('tamanho', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('FALHA', 'Falha')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('erro', models.TextField(blank=True, null=True, verbose_name='Erro')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave', models.CharField(choices=[('NOME_CLUBE', 'Nome do Clube'), ('LOGO_CLUBE', 'Logo do Clube'), ('ENDERECO_CLUBE', 'Endereço do Clube'), ('TELEFONE_CLUBE', 'Telefone do Clube'), ('EMAIL_CLUBE', 'E-mail do Clube'), ('CNPJ_CLUBE', 'CNPJ do Clube'), ('DIA_VENCIMENTO_MENSALIDADE', 'Dia de Vencimento da Mensalidade'), ('VALOR_MENSALIDADE_PADRAO', 'Valor da Mensalidade Padrão'), ('PERMITIR_CANCELAMENTO_MENSALIDADE', 'Permitir Cancelamento de Mensalidade'), ('DIAS_TOLERANCIA_MENSALIDADE', 'Dias de Tolerância para Mensalidade'), ('PERCENTUAL_JUROS_ATRASO', 'Percentual de Juros por Atraso'), ('EMAIL_NOTIFICACOES', 'E-mail para Notificações'), ('WHATSAPP_API_TOKEN', 'Token da API do WhatsApp'), ('WHATSAPP_API_URL', 'URL da API do WhatsApp'), ('SMTP_HOST', 'Servidor SMTP'), ('SMTP_PORT', 'Porta SMTP'), ('SMTP_USER', 'Usuário SMTP'), ('SMTP_PASSWORD', 'Senha SMTP'), ('SMTP_USE_TLS', 'Usar TLS no SMTP'), ('GOOGLE_ANALYTICS_ID', 'ID do Google Analytics'), ('FACEBOOK_PIXEL_ID', 'ID do Facebook Pixel')], max_length=100, unique=True, verbose_name='Chave')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'ordering': ['chave'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('INFO', 'Informação'), ('SUCCESS', 'Sucesso'), ('WARNING', 'Aviso'), ('ERROR', 'Erro')], default='INFO', max_length=20, verbose_name='Tipo')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('NAO_LIDA', 'Não Lida'), ('LIDA', 'Lida'), ('ARQUIVADA', 'Arquivada')], default='NAO_LIDA', max_length=20, verbose_name='Status')),
                ('link_acao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link de Ação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('data_arquivamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Arquivamento')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
