# Generated by Django 5.2.5 on 2025-09-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empresa_cidade_alter_empresa_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='empresa_contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
