# Generated by Django 5.2.5 on 2025-08-14 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Sócio',
                'verbose_name_plural': 'Categorias de Sócios',
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('empresa_contato', models.CharField(blank=True, max_length=100)),
                ('telefone_contato', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.IntegerField(help_text='Número de registro único do sócio.', unique=True)),
                ('num_contrato', models.IntegerField(blank=True, help_text='Número do contrato, se aplicável.', null=True, unique=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('apelido', models.CharField(blank=True, max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('nacionalidade', models.CharField(blank=True, default='Brasileira', max_length=100)),
                ('naturalidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade Natal')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO', 'União Estável')], max_length=10)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('nome_pai', models.CharField(blank=True, max_length=255, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(blank=True, max_length=255, verbose_name='Nome da Mãe')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('tel_residencial', models.CharField(blank=True, max_length=20, verbose_name='Telefone Residencial')),
                ('tel_trabalho', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Trabalho')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço (Rua, Nº)')),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('data_admissao', models.DateField(default=django.utils.timezone.now)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('SUSPENSO', 'Suspenso'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_socios/')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='socios', to='core.categoriasocio')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socios', to='core.convenio')),
            ],
            options={
                'verbose_name': 'Sócio',
                'verbose_name_plural': 'Sócios',
                'ordering': ['nome'],
            },
        ),
    ]
