# Generated by Django 5.2.4 on 2026-09-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_convenio_empresa_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='dia_vencimento',
            field=models.PositiveIntegerField(default=10, help_text='Dia do mês em que vence (ex: 10). Se 0, usa o da categoria.', verbose_name='Dia do Vencimento'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor cobrado dos sócios deste convênio. Se 0, usa o valor da categoria.', max_digits=10, verbose_name='Valor da Mensalidade (Convênio)'),
        ),
    ]
