# Generated by Django 5.2.5 on 2025-08-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoriasocio_convenio_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('responsavel', models.CharField(blank=True, max_length=150, verbose_name='Responsável')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço (Rua, Nº, Bairro)')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/', verbose_name='Logotipo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
