# Generated by Django 5.2.5 on 2025-08-14 14:41

import localflavor.br.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('parentesco', models.CharField(choices=[('CONJUGE', 'Cônjuge'), ('FILHO', 'Filho(a)'), ('ENTEADO', 'Enteado(a)'), ('PAI', 'Pai'), ('MAE', 'Mãe'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Parentesco')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Tipo Sanguíneo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='socios/dependentes/fotos/', verbose_name='Foto')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Dependente',
                'verbose_name_plural': 'Dependentes',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='InteracaoSocio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TELEFONE', 'Telefone'), ('EMAIL', 'E-mail'), ('PRESENCIAL', 'Presencial'), ('WHATSAPP', 'WhatsApp'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Interação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_interacao', models.DateTimeField(verbose_name='Data da Interação')),
                ('proximo_contato', models.DateField(blank=True, null=True, verbose_name='Próximo Contato')),
            ],
            options={
                'verbose_name': 'Interação com Sócio',
                'verbose_name_plural': 'Interações com Sócios',
                'ordering': ['-data_interacao'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[localflavor.br.validators.BRCPFValidator()], verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável')], default='SOLTEIRO', max_length=20, verbose_name='Estado Civil')),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Tipo Sanguíneo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Secundário')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='socios/fotos/', verbose_name='Foto')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Sócio',
                'verbose_name_plural': 'Sócios',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
