# Generated by Django 5.2.5 on 2025-08-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacaosocio',
            name='socio',
        ),
        migrations.RemoveField(
            model_name='interacaosocio',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='cadastrado_por',
        ),
        migrations.DeleteModel(
            name='Dependente',
        ),
        migrations.DeleteModel(
            name='InteracaoSocio',
        ),
        migrations.DeleteModel(
            name='Socio',
        ),
    ]
