# Generated by Django 5.2.5 on 2025-08-14 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaCobranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Campanha')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVO', 'Ativo'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('filtro_status_mensalidade', models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], max_length=20, null=True, verbose_name='Filtrar por Status da Mensalidade')),
                ('filtro_dias_atraso', models.IntegerField(blank=True, null=True, verbose_name='Filtrar por Dias de Atraso')),
                ('total_envios', models.IntegerField(default=0, verbose_name='Total de Envios')),
                ('total_sucesso', models.IntegerField(default=0, verbose_name='Total de Sucessos')),
                ('total_falhas', models.IntegerField(default=0, verbose_name='Total de Falhas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Campanha de Cobrança',
                'verbose_name_plural': 'Campanhas de Cobrança',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='EnvioCobranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('FALHA', 'Falha'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('conteudo_enviado', models.TextField(blank=True, null=True, verbose_name='Conteúdo Enviado')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('resposta', models.TextField(blank=True, null=True, verbose_name='Resposta')),
                ('erro', models.TextField(blank=True, null=True, verbose_name='Erro')),
                ('tentativas', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Envio de Cobrança',
                'verbose_name_plural': 'Envios de Cobrança',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoCobranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('ENVIO_COBRANCA', 'Envio de Cobrança'), ('CONTATO_TELEFONICO', 'Contato Telefônico'), ('VISITA', 'Visita'), ('NEGOCIACAO', 'Negociação'), ('PAGAMENTO', 'Pagamento'), ('ACORDO', 'Acordo')], max_length=20, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_acao', models.DateTimeField(verbose_name='Data da Ação')),
                ('proximo_passo', models.TextField(blank=True, null=True, verbose_name='Próximo Passo')),
                ('data_proximo_passo', models.DateTimeField(blank=True, null=True, verbose_name='Data do Próximo Passo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Histórico de Cobrança',
                'verbose_name_plural': 'Históricos de Cobrança',
                'ordering': ['-data_acao'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCobranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('tipo', models.CharField(choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('CARTA', 'Carta')], max_length=20, verbose_name='Tipo de Template')),
                ('assunto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Assunto')),
                ('template', models.TextField(verbose_name='Template')),
                ('variaveis_disponiveis', models.TextField(blank=True, help_text='Lista de variáveis que podem ser usadas no template', null=True, verbose_name='Variáveis Disponíveis')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Template de Cobrança',
                'verbose_name_plural': 'Templates de Cobrança',
                'ordering': ['nome'],
            },
        ),
    ]
