# Generated by Django 5.2.5 on 2025-08-14 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranca', '0001_initial'),
        ('financeiro', '0001_initial'),
        ('socios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhacobranca',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='campanhacobranca',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, related_name='campanhas_recebidas', to='socios.socio', verbose_name='Destinatários'),
        ),
        migrations.AddField(
            model_name='enviocobranca',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='cobranca.campanhacobranca', verbose_name='Campanha'),
        ),
        migrations.AddField(
            model_name='enviocobranca',
            name='mensalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_cobranca', to='financeiro.mensalidade', verbose_name='Mensalidade'),
        ),
        migrations.AddField(
            model_name='enviocobranca',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_cobranca', to='socios.socio', verbose_name='Sócio'),
        ),
        migrations.AddField(
            model_name='historicocobranca',
            name='mensalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_cobranca', to='financeiro.mensalidade', verbose_name='Mensalidade'),
        ),
        migrations.AddField(
            model_name='historicocobranca',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_cobranca', to='socios.socio', verbose_name='Sócio'),
        ),
        migrations.AddField(
            model_name='historicocobranca',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_cobranca_registrado', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='campanhacobranca',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas', to='cobranca.templatecobranca', verbose_name='Template'),
        ),
        migrations.AlterUniqueTogether(
            name='enviocobranca',
            unique_together={('campanha', 'socio', 'mensalidade')},
        ),
    ]
