# Generated by Django 5.2.5 on 2025-08-19 20:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=7)),
            ],
            options={
                'verbose_name': 'Categoria de Transação',
                'verbose_name_plural': 'Categorias de Transações',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_transacao', models.DateField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriatransacao')),
                ('socio', models.ForeignKey(blank=True, help_text='Opcional, se a transação for ligada a um sócio específico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.socio')),
            ],
            options={
                'verbose_name': 'Transação Avulsa',
                'verbose_name_plural': 'Transações Avulsas',
                'ordering': ['-data_transacao'],
            },
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(default=django.utils.timezone.now, verbose_name='Mês de Competência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('ATRASADA', 'Atrasada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensalidades', to='core.socio')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
                'unique_together': {('socio', 'competencia')},
            },
        ),
    ]
