# Generated by Django 5.2.5 on 2026-02-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Opcional. Use para contas a pagar.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
    ]
