# Generated by Django 5.2.5 on 2025-08-14 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
        ('socios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='gerado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensalidades_geradas', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='pago_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensalidades_pagas', to=settings.AUTH_USER_MODEL, verbose_name='Pago por'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='socios.socio', verbose_name='Sócio'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensalidades', to='financeiro.planomensalidade', verbose_name='Plano'),
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='financeiro.categoriareceita', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='receita',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='mensalidade',
            unique_together={('socio', 'referencia')},
        ),
    ]
