# Generated by Django 5.2.5 on 2026-08-24 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_conta_fornecedor'),
        ('formas_pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formas_pagamento.formapagamento', verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='competencia',
            field=models.DateField(verbose_name='Mes de Competencia'),
        ),
    ]
