# Generated by Django 5.2.4 on 2026-09-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_convenio_dia_vencimento_convenio_valor_mensalidade'),
        ('financeiro', '0003_mensalidade_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Doc / Parcela'),
        ),
        migrations.AddField(
            model_name='conta',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Pago'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='socio',
            field=models.ForeignKey(blank=True, help_text='Opcional - Cliente (Receber)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.socio'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcialmente Paga'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10),
        ),
    ]
